### PR TITLE
get a static function for a regression

### PR DESCRIPTION
**Pull request by lpatiny**

### CODE REVIEW

**Comment by lpatiny** [comment]
I would like to be able to get a prediction function that can be reused outside the context of 'regression' and don't know if this make sense @targos

**Comment by targos** [comment]
You can do it with bind: `const predict = regression.predict.bind(regression)`

**Review by targos — CHANGES_REQUESTED** [review]
There's another way

**Comment by lpatiny** [comment]
Would this make sense to add this in `BaseRegression` or it is too obvious ?

**Comment by targos** [comment]
I think it's too basic to be worth

**Pull request closed without merging**
